In [1]:
import pandas as pd

import sys
import sklearn.neighbors._base
sys.modules['sklearn.neighbors.base'] = sklearn.neighbors._base
from missingpy import MissForest

%load_ext autotime

time: 131 Âµs (started: 2022-05-08 01:30:45 +04:00)

In [2]:
filepath = "../Data/TrainDataSample.csv"

train_data = pd.read_csv(filepath)

filepath = "../Data/TestDataSample.csv"

test_data = pd.read_csv(filepath)

time: 2.8 s (started: 2022-05-08 01:30:45 +04:00)

In [3]:
# Using MissForest to impute missing values of the train dataset.

imputer = MissForest(random_state=42)
train_X_imputed = imputer.fit_transform(train_data)

Iteration: 0
Iteration: 1
Iteration: 2
Iteration: 3
Iteration: 4
time: 10h 12min 43s (started: 2022-05-08 01:30:48 +04:00)

In [4]:
# Using MissForest to impute missing values of the test dataset.

imputer = MissForest(random_state=42)
test_X_imputed = imputer.fit_transform(test_data)

Iteration: 0
Iteration: 1
Iteration: 2
Iteration: 3
Iteration: 4
time: 4h 23min 50s (started: 2022-05-08 11:43:33 +04:00)

In [5]:
# transforming to dataframe scaled columns which are already imputed, replacing main dataframes columns by imputed columns.

scaled_data_for_mf = pd.DataFrame(train_X_imputed, index=train_data.index, columns=train_data.columns)
train_data[scaled_data_for_mf.columns] = scaled_data_for_mf
train_data[scaled_data_for_mf.columns]

,NumberOfOpenBankcardTrades,AnnualPercentageRate,TimesTargeted,Balance,Age,MonthsOnFile,OfferRate,SumBalanceAuto,MonthsSinceOpen,Payment,...,NumberOfTradelines,AllLoansPaidAsAgreed,PErsonalLoanSumHighCredit,PErsonalLoanSumPayment,AutoTradeline,KeycodedPresenceOfAFinanceTradeOrInquiry,TermChange,NumOfMortgageTrades,Lead Flag,ZIPCode
0,0.0,23.39,2.0,29062.0,38.0,139.0,10.96,29062.0,10.0,757.0,...,2.0,0.35,9945.512147,2895.015881,1.0,0.0,9.0,0.0,0.0,36108.0
1,3.0,13.53,0.0,35015.0,61.0,288.0,11.45,35015.0,9.0,740.0,...,1.0,0.35,9945.512147,2895.015881,1.0,1.0,7.0,3.0,0.0,92571.0
2,0.0,9.57,4.0,19592.0,61.0,171.0,7.29,19592.0,21.0,453.0,...,1.0,0.53,21733.000000,16654.000000,1.0,1.0,12.0,0.0,0.0,76904.0
3,1.0,17.30,0.0,23529.0,32.0,117.0,0.00,22183.0,2.0,536.0,...,3.0,0.40,9945.512147,2895.015881,1.0,0.0,0.0,0.0,0.0,67846.0
4,3.0,7.86,1.0,22357.0,37.0,309.0,5.69,36687.0,10.0,418.0,...,4.0,1.00,9945.512147,2895.015881,2.0,0.0,8.0,1.0,0.0,97303.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
638929,2.0,7.94,0.0,26520.0,44.0,183.0,3.74,46001.0,12.0,523.0,...,4.0,1.00,4592.000000,2895.015881,1.0,1.0,11.0,1.0,1.0,21060.0
638930,3.0,14.32,1.0,15167.0,66.0,158.0,4.50,59067.0,14.0,360.0,...,3.0,0.61,9945.512147,2895.015881,2.0,0.0,12.0,0.0,1.0,91911.0
638931,4.0,12.42,0.0,42329.0,54.0,178.0,3.00,58689.0,10.0,888.0,...,4.0,0.71,18695.000000,1522.000000,1.0,1.0,9.0,0.0,1.0,73110.0
638932,1.0,15.04,0.0,33758.0,47.0,287.0,4.50,34386.0,9.0,706.0,...,3.0,0.56,9945.512147,2895.015881,1.0,0.0,3.0,1.0,1.0,77429.0
638933,1.0,20.55,5.0,30340.0,40.0,24.0,8.28,37225.0,12.0,787.0,...,2.0,1.00,9945.512147,2895.015881,1.0,0.0,11.0,0.0,1.0,77407.0

time: 589 ms (started: 2022-05-08 16:07:24 +04:00)

In [6]:
# transforming to dataframe scaled columns which are already imputed, replacing main dataframes columns by imputed columns.

scaled_data_for_mf = pd.DataFrame(test_X_imputed, index=test_data.index, columns=test_data.columns)
test_data[scaled_data_for_mf.columns] = scaled_data_for_mf
test_data[scaled_data_for_mf.columns]

,NumberOfOpenBankcardTrades,AnnualPercentageRate,TimesTargeted,Balance,Age,MonthsOnFile,OfferRate,SumBalanceAuto,MonthsSinceOpen,Payment,...,NumberOfTradelines,AllLoansPaidAsAgreed,PErsonalLoanSumHighCredit,PErsonalLoanSumPayment,AutoTradeline,KeycodedPresenceOfAFinanceTradeOrInquiry,TermChange,NumOfMortgageTrades,Lead Flag,ZIPCode
0,3.0,9.71,0.0,21122.0,45.466302,168.0,3.0000,16823.0,9.0,427.0,...,3.0,0.58,433.000000,29.000000,1.0,1.0,8.0,0.0,0.0,91106.0
1,2.0,8.89,3.0,16178.0,23.000000,61.0,5.6300,16178.0,15.0,334.0,...,1.0,1.00,9945.512147,2895.015881,1.0,0.0,12.0,0.0,0.0,33143.0
2,2.0,14.41,2.0,20688.0,26.000000,26.0,8.6500,20688.0,10.0,447.0,...,1.0,0.97,9945.512147,2895.015881,1.0,0.0,5.0,0.0,0.0,60707.0
3,0.0,5.01,2.0,28779.0,31.000000,140.0,3.7600,28779.0,11.0,538.0,...,2.0,0.99,7.000000,2895.015881,1.0,1.0,10.0,0.0,0.0,49920.0
4,0.0,24.94,0.0,17272.0,50.000000,90.0,11.8600,17272.0,22.0,448.0,...,1.0,1.00,9945.512147,2895.015881,1.0,0.0,12.0,0.0,0.0,33155.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314694,1.0,10.63,0.0,16743.0,36.000000,204.0,4.5000,17858.0,11.0,347.0,...,5.0,1.00,9945.512147,2895.015881,1.0,1.0,10.0,0.0,1.0,18976.0
314695,2.0,11.61,0.0,23733.0,58.000000,336.0,0.0474,24312.0,28.0,650.0,...,4.0,0.53,9945.512147,2895.015881,2.0,0.0,12.0,1.0,1.0,30004.0
314696,1.0,16.28,1.0,24255.0,50.000000,360.0,10.1900,24255.0,15.0,582.0,...,1.0,1.00,9945.512147,2895.015881,1.0,0.0,12.0,0.0,1.0,99654.0
314697,0.0,17.57,0.0,19706.0,48.000000,83.0,6.5000,19706.0,16.0,490.0,...,1.0,0.00,3754.000000,919.000000,1.0,1.0,12.0,0.0,1.0,29646.0
314698,5.0,8.90,0.0,24901.0,38.000000,209.0,7.3800,24901.0,13.0,501.0,...,2.0,0.00,9945.512147,2895.015881,1.0,0.0,12.0,0.0,1.0,80916.0

time: 156 ms (started: 2022-05-08 16:07:24 +04:00)

In [7]:
# Concatinating train and test dataframes to check if there are any 0s.

data = pd.concat([train_data, test_data])

Nas = []
count_rows = data.shape[0]
for col in data.columns:
    count_nan = data[col].isna().sum() / count_rows * 100
    Nas.append(count_nan)
NAs_df = pd.DataFrame({'cols':data.columns, 'Nas_perc':Nas})
NAs_df = NAs_df.sort_values(by=['Nas_perc'], ascending=False)
NAs_df

                                              cols  Nas_perc
0                       NumberOfOpenBankcardTrades       0.0
1                             AnnualPercentageRate       0.0
28                                 NumOfChargeOffs       0.0
29                                    TermInMonths       0.0
30                        AgeOfOldestBankcardTrade       0.0
31                               MailType_Standard       0.0
32                          PErsonalLoanSumBalance       0.0
33                             3MonthFICOAutoDelta       0.0
34                       AgeOfOLdestRevolvingTrade       0.0
35  Monthlypaymentamountofhighestmortgagetrade_1MO       0.0
36             MonthsSinceMostRecentMortgageOpened       0.0
37                   NumberOfBankruptciesDismissed       0.0
38                                    OfferPayment       0.0
39         AgeOfOldestOpenAndCurrentRevolvingTrade       0.0
40                                       OfferTerm       0.0
41          AggBalToCreditRatioForOpenRetailTrades       0.0
42                              NumberOfTradelines       0.0
43                            AllLoansPaidAsAgreed       0.0
44                       PErsonalLoanSumHighCredit       0.0
45                          PErsonalLoanSumPayment       0.0
46                                   AutoTradeline       0.0
47        KeycodedPresenceOfAFinanceTradeOrInquiry       0.0
48                                      TermChange       0.0
49                             NumOfMortgageTrades       0.0
50                                       Lead Flag       0.0
27                           MortgageSumHighCredit       0.0
26                        NumberOfInquiries6Months       0.0
25             NumberOfNonAutoLoanAndLease12Months       0.0
12                                   PaymentChange       0.0
2                                    TimesTargeted       0.0
3                                          Balance       0.0
4                                              Age       0.0
5                                     MonthsOnFile       0.0
6                                        OfferRate       0.0
7                                   SumBalanceAuto       0.0
8                                  MonthsSinceOpen       0.0
9                                          Payment       0.0
10                     AggMonthlyPaymentOpenTrades       0.0
11       NumOfTradesOpenedWithin24MosExStudentLoan       0.0
13                                 RemainingMonths       0.0
24                                  FICO8AutoScore       0.0
14                                  SumPaymentAuto       0.0
15                    MostRecentOpenedinMonthsAuto       0.0
16                                      RateChange       0.0
17                    MostRecentClosedinMonthsAuto       0.0
18        AggregateBalanceOpenRevolvingNonMortgage       0.0
19                    HighestRevolvingCreditAmount       0.0
20                     AgeOfMostRecentFinanceTrade       0.0
21                  NumberOfBankruptciesDischarged       0.0
22                                   FICOAutoScore       0.0
23           HighestBankcardSingleBalToCreditRatio       0.0
51                                         ZIPCode       0.0

time: 200 ms (started: 2022-05-08 16:07:24 +04:00)

In [8]:
# Saving train and test datasets.

train_data.to_csv('../Data/TrainDataMf.csv', index=False) 
test_data.to_csv('../Data/TestDataMf.csv', index=False)

time: 39.5 s (started: 2022-05-08 16:07:24 +04:00)